import "./globals.css";
import { cn } from "@lib/utils";
import Navbar from "@components/Navbar";
import { cookies } from "next/dist/client/components/headers";
import Toast from "@components/Toast";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = cookies().get("theme");

  return (
    <html lang="en" className={cn(theme?.value || "dark")}>
      <body className={cn("p-0 flex flex-col min-h-screen")}>
        <Navbar theme={theme?.value} />

        {children}

        <Toast />
      </body>
    </html>
  );
}
